/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * HT Server API
 * API documentation for HT Server
 * OpenAPI spec version: 1.0
 */
import type { HomeResponse } from '../../../types/api';
import { apiClient } from '../axios-client-config';

import { apiServer } from '../axios-server-config';

/**
 * 인증된 사용자의 홈 화면 데이터를 조회합니다
 * @summary 홈 화면 데이터 조회
 */
export const getHomeData = () => {
  return apiClient<HomeResponse>({ url: `/home`, method: 'GET' });
};
export type GetHomeDataResult = NonNullable<
  Awaited<ReturnType<typeof getHomeData>>
>;
