/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * HT Server API
 * API documentation for HT Server
 * OpenAPI spec version: 1.0
 */
import type { ImageRequestDto } from './imageRequestDto';
import type { VideoRequestDto } from './videoRequestDto';

/**
 * 영상 생성 요청
 */
export interface CreateVideoGenerationRequest {
  /** 영상에 대한 상세 설명 */
  text: string;
  /** 사용할 이미지 목록 */
  images: ImageRequestDto[];
  /** 사용할 비디오 목록 */
  videos: VideoRequestDto[];
  /** 가게 ID */
  storeId: string;
}
