/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * HT Server API
 * API documentation for HT Server
 * OpenAPI spec version: 1.0
 */

/**
 * 영상 생성 요청 응답
 */
export interface CreateVideoGenerationResponse {
  /** 영상 생성 요청 ID */
  videoGenerationId?: string;
}
