/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * HT Server API
 * API documentation for HT Server
 * OpenAPI spec version: 1.0
 */

export interface CreateStoreResponse {
  id?: string;
  name?: string;
  address?: string;
  description?: string;
  naverUrl?: string;
}
