/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * HT Server API
 * API documentation for HT Server
 * OpenAPI spec version: 1.0
 */
import type { Video } from './video';

export interface HomeResponse {
  videos?: Video[];
  mostRecentViews?: number;
}
