/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * HT Server API
 * API documentation for HT Server
 * OpenAPI spec version: 1.0
 */

/**
 * 이미지 요청 정보
 */
export interface ImageRequestDto {
  /** 이미지 이름 */
  name: string;
  /** 이미지 URL */
  imageUrl: string;
}
