/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * HT Server API
 * API documentation for HT Server
 * OpenAPI spec version: 1.0
 */

/**
 * 카카오 Authorization Code로 로그인 요청
 */
export interface KakaoLoginRequest {
  /** 카카오 OAuth Authorization Code */
  authorizationCode: string;
}
