/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * HT Server API
 * API documentation for HT Server
 * OpenAPI spec version: 1.0
 */

/**
 * JWT 액세스 토큰을 포함하는 로그인 응답
 */
export interface LoginResponse {
  /** JWT 액세스 토큰 */
  accessToken?: string;
}
