/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * HT Server API
 * API documentation for HT Server
 * OpenAPI spec version: 1.0
 */
import type { User } from './user';
import type { Video } from './video';
import type { VideoGeneration } from './videoGeneration';

export interface Store {
  id?: string;
  createdAt?: string;
  updatedAt?: string;
  name?: string;
  address?: string;
  description?: string;
  naverUrl?: string;
  user?: User;
  videos?: Video[];
  videoGenerations?: VideoGeneration[];
}
