/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * HT Server API
 * API documentation for HT Server
 * OpenAPI spec version: 1.0
 */
import type { UpdateUserOnboardingStatusRequestRole } from './updateUserOnboardingStatusRequestRole';

/**
 * 유저 온보딩 정보 업데이트 요청
 */
export interface UpdateUserOnboardingStatusRequest {
  /** 유저 닉네임 */
  nickname: string;
  /** 유저 권한 */
  role: UpdateUserOnboardingStatusRequestRole;
  /** 쇼츠테이블 서비스 이용약관 */
  termsOfServiceAccepted: boolean;
  /** 개인정보 수집 및 이용동의 */
  privacyPolicyAccepted: boolean;
  /** 위치기반 서비스 이용동의 */
  locationServiceAccepted?: boolean;
}
