/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * HT Server API
 * API documentation for HT Server
 * OpenAPI spec version: 1.0
 */

/**
 * 유저 권한
 */
export type UpdateUserOnboardingStatusRequestRole = typeof UpdateUserOnboardingStatusRequestRole[keyof typeof UpdateUserOnboardingStatusRequestRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateUserOnboardingStatusRequestRole = {
  USER: 'USER',
  ADMIN: 'ADMIN',
  SUPERADMIN: 'SUPERADMIN',
} as const;
