/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * HT Server API
 * API documentation for HT Server
 * OpenAPI spec version: 1.0
 */
import type { UserRole } from './userRole';
import type { Store } from './store';

export interface User {
  id?: string;
  createdAt?: string;
  updatedAt?: string;
  kakaoId?: string;
  email?: string;
  profileImageUrl?: string;
  nickname?: string;
  role?: UserRole;
  termsOfServiceAccepted?: boolean;
  privacyPolicyAccepted?: boolean;
  locationServiceAccepted?: boolean;
  stores?: Store[];
}
