/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * HT Server API
 * API documentation for HT Server
 * OpenAPI spec version: 1.0
 */
import type { VideoGeneration } from './videoGeneration';

export interface VideoRequest {
  id?: string;
  createdAt?: string;
  updatedAt?: string;
  videoUrl?: string;
  videoGeneration?: VideoGeneration;
}
