/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * HT Server API
 * API documentation for HT Server
 * OpenAPI spec version: 1.0
 */

/**
 * 영상 정보 응답
 */
export interface VideoResponse {
  /** 영상 URL */
  videoUrl?: string;
  /** 가게 주소 */
  address?: string;
  /** 가게 이름 */
  storeName?: string;
  /** 조회수 */
  views?: number;
  /** 영상 생성 시간 */
  createdAt?: string;
}
