/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * HT Server API
 * API documentation for HT Server
 * OpenAPI spec version: 1.0
 */

export type VideoGenerationStatus = typeof VideoGenerationStatus[keyof typeof VideoGenerationStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const VideoGenerationStatus = {
  IDLE: 'IDLE',
  IN_PROGRESS: 'IN_PROGRESS',
  FINISHED: 'FINISHED',
  FAILED: 'FAILED',
} as const;
