/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * HT Server API
 * API documentation for HT Server
 * OpenAPI spec version: 1.0
 */
import type { VideoGenerationStatus } from './videoGenerationStatus';
import type { ImageRequest } from './imageRequest';
import type { VideoRequest } from './videoRequest';
import type { Video } from './video';
import type { Store } from './store';

export interface VideoGeneration {
  id?: string;
  createdAt?: string;
  updatedAt?: string;
  text?: string;
  status?: VideoGenerationStatus;
  images?: ImageRequest[];
  videos?: VideoRequest[];
  video?: Video;
  store?: Store;
}
