/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * HT Server API
 * API documentation for HT Server
 * OpenAPI spec version: 1.0
 */

export interface Video {
  id?: string;
  createdAt?: string;
  address?: string;
  videoUrl?: string;
  views?: number;
  storeName?: string;
}
