/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * HT Server API
 * API documentation for HT Server
 * OpenAPI spec version: 1.0
 */

/**
 * 비디오 요청 정보
 */
export interface VideoRequestDto {
  /** 비디오 URL */
  videoUrl: string;
}
