/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * HT Server API
 * API documentation for HT Server
 * OpenAPI spec version: 1.0
 */
import type { VideoGenerationStatusResponseStatus } from './videoGenerationStatusResponseStatus';
import { VideoResponse } from './videoResponse';

/**
 * 영상 생성 상태 응답
 */
export interface VideoGenerationStatusResponse {
  /** 영상 생성 요청 ID */
  videoGenerationId?: string;
  /** 영상 생성 상태 */
  status?: VideoGenerationStatusResponseStatus;
  /** 요청 생성 시간 */
  createdAt?: string;
  /** 생성된 영상 URL */
  generatedVideoUrl?: string;
  /** 오류 메시지 */
  errorMessage?: string;
  video?: {
    id: string;
    videoUrl: string;
    address: string;
    storeName: string;
    views: number;
    createdAt: string;
  };
}
