/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * HT Server API
 * API documentation for HT Server
 * OpenAPI spec version: 1.0
 */

/**
 * 영상 생성 상태
 */
export type VideoGenerationStatusResponseStatus = typeof VideoGenerationStatusResponseStatus[keyof typeof VideoGenerationStatusResponseStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const VideoGenerationStatusResponseStatus = {
  IDLE: 'IDLE',
  IN_PROGRESS: 'IN_PROGRESS',
  FINISHED: 'FINISHED',
  FAILED: 'FAILED',
} as const;
